### ISSUE TITLE
Criação de arquivo genérico para erros

### ISSUE THREAD

**Issue by gksouza** [gksouza/api-food-explorer#3]
- [x] Criar a pasta utils
- [x] Criar arquivo AppError.js

**Em src\services\UserCreateService.js:**
- [x] Habilitar a linha 12 e apagar a linha 14

**No arquivo server.js depois do import da migrationsRun adicionar:**
- [x] const AppError = require("./utils/AppError");
- [x] Depois da linha 9 adicionar:
> app.use((error, request, response, next) => {
>   if(error instanceof AppError) {
>     return response.status(error.statusCode).json({
>       status: "error",
>       message: error.message
>     });
>   }
> 
>   console.error(error);
> 
>   return response.status(500).json({
>     status: "error",
>     message: "Internal server error",
>   });
> })
> ;
- [x] Por último, voltar ao Insomnia e executar novamente a criação de um usuário com os mesmos dados
> Esperado no retorno do Insomnia:
> Msg: "Este e-mail já está em uso." **(erro -- vide prints abaixo)**

**Comment by gksouza** [comment]
Novo usuário criado com sucesso, porém ao clicar em SEND novamente, ocorreu esse erro:
![image](https://github.com/gksouza/api-food-explorer/assets/106996981/890c22be-5731-4d41-afe4-37f4db44a793)

**Comment by gksouza** [comment]
O erro foi tratado alterando o código de:

![image](https://github.com/gksouza/api-food-explorer/assets/106996981/03e157af-a759-4f55-b186-f4da943fd942)

Para (incluídos request e next):

![image](https://github.com/gksouza/api-food-explorer/assets/106996981/aa8cff2e-fcf3-4bd9-b853-096e4d72f8b2)


Print do erro corrigido:

![image](https://github.com/gksouza/api-food-explorer/assets/106996981/f0560f63-e2ec-46b0-96d9-3051d256fb29)

**Comment by gksouza** [comment]
Errors antes do [object Object]:

ReferenceError: AppError is not defined
    at UserCreateService.execute (D:\EXPLORER\api-food-explorer\src\services\UserCreateService.js:12:27)
    **Solução:** A linha do AppError estava comentada e após retirar o comentário esse erro foi solucionado.
    
at async create (D:\EXPLORER\api-food-explorer\src\controllers\usersController.js:11:5)
    **Solução:** erro tratado conforme os comentários acima.
    
### **_TASK ENCERRADA EM 21/03/24_**
